// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trrneweqpzeojoxdprxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRycm5ld2VxcHplb2pveGRwcnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzM3MTksImV4cCI6MjA3MDg0OTcxOX0.G-9_GXh3Anef1qdSPryUUF_7aN3R5i5mYFrmMhFbOjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});